excerpt_separator: ""
pygments: true
markdown: kramdown
url: http://f-ds.github.io
title: f-ds
tagline: fds dev blog
description: Everyday GIS stuff and Backend programming for food
paginate: 5
